# Generated by Django 2.0.7 on 2019-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresaDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutEmpresa', models.CharField(max_length=70)),
                ('nombreEmpresa', models.CharField(max_length=70)),
                ('giroEmpresa', models.CharField(max_length=70)),
                ('dirEmpresa', models.CharField(max_length=150)),
                ('userEmpresa', models.CharField(max_length=100)),
                ('passEmpresa', models.CharField(max_length=50)),
            ],
        ),
    ]
