# Generated by Django 2.0.7 on 2019-11-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comedorDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPlato', models.CharField(max_length=70)),
                ('entrada', models.CharField(max_length=70)),
                ('platoFondo', models.CharField(max_length=70)),
                ('postre', models.CharField(max_length=70)),
                ('valorMenu', models.IntegerField()),
            ],
        ),
    ]
