# Generated by Django 2.0.7 on 2019-11-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_auto_20191113_0207'),
        ('registro', '0002_comedordatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_Emp_Fac', models.CharField(max_length=70)),
                ('nombre_Emp_Fac', models.CharField(max_length=70)),
                ('giro_Emp_Fac', models.CharField(max_length=70)),
                ('dir_Emp_Fac', models.CharField(max_length=70)),
                ('valor_Serv_Fac', models.IntegerField()),
                ('valor_Hab_Fac', models.IntegerField()),
                ('total_Fac', models.IntegerField()),
                ('tipo_Hab_Fac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registro.comedorDatos')),
                ('tipo_Serv_Fac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
            ],
        ),
    ]
