# Generated by Django 2.0.7 on 2019-11-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_facturadatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadatos',
            name='tipo_Hab_Fac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion'),
        ),
        migrations.AlterField(
            model_name='facturadatos',
            name='tipo_Serv_Fac',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registro.comedorDatos'),
        ),
    ]
