# Generated by Django 2.2.7 on 2019-11-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoCama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descCama', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroHabitacion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('tipoCama', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.tipoCama')),
            ],
        ),
    ]
