# Generated by Django 2.2.7 on 2019-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='accesorios',
            field=models.CharField(default='Lampara', max_length=70),
        ),
    ]
