# Generated by Django 2.2.7 on 2019-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='accesorios',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
