# Generated by Django 2.2.7 on 2019-11-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_auto_20191113_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoHab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descEstado', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.estadoHab'),
        ),
    ]
