# Generated by Django 2.0.7 on 2019-11-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_auto_20191113_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='tipoHabitacion',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
